# Generated by Django 5.1 on 2025-04-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='perfil_pics'),
        ),
    ]
